In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
df=pd.read_csv("glass.csv")
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [2]:
scaler = StandardScaler()
print(scaler.fit_transform(df))

[[-1.72397593  0.87286765  0.28495326 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.70778837 -0.24933347  0.59181718 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.6916008  -0.72131806  0.14993314 ... -0.35287683 -0.5864509
  -0.84827468]
 ...
 [ 1.6916008   0.75404635  1.16872135 ...  2.95320036 -0.5864509
   2.01047778]
 [ 1.70778837 -0.61239854  1.19327046 ...  2.81208731 -0.5864509
   2.01047778]
 [ 1.72397593 -0.41436305  1.00915211 ...  3.01367739 -0.5864509
   2.01047778]]


In [3]:
X = df.drop('Type', axis=1)
y = df['Type']

In [4]:
X.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [5]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Type, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.3 )

In [7]:
svclassifier = SVC(kernel='linear')

In [8]:
svclassifier.fit(X_train,y_train)

SVC(kernel='linear')

In [9]:
y_preds = svclassifier.predict(X_test)

In [10]:
accuracy_score(y_test,y_preds)

1.0

In [11]:
svclassifier.support_vectors_[:5]

array([[7.00000e+01, 1.52300e+00, 1.33100e+01, 3.58000e+00, 8.20000e-01,
        7.19900e+01, 1.20000e-01, 1.01700e+01, 0.00000e+00, 3.00000e-02],
       [7.20000e+01, 1.51848e+00, 1.36400e+01, 3.87000e+00, 1.27000e+00,
        7.19600e+01, 5.40000e-01, 8.32000e+00, 0.00000e+00, 3.20000e-01],
       [1.46000e+02, 1.51839e+00, 1.28500e+01, 3.67000e+00, 1.24000e+00,
        7.25700e+01, 6.20000e-01, 8.68000e+00, 0.00000e+00, 3.50000e-01],
       [1.61000e+02, 1.51832e+00, 1.33300e+01, 3.34000e+00, 1.54000e+00,
        7.21400e+01, 5.60000e-01, 8.99000e+00, 0.00000e+00, 0.00000e+00],
       [1.47000e+02, 1.51769e+00, 1.36500e+01, 3.66000e+00, 1.11000e+00,
        7.27700e+01, 1.10000e-01, 8.60000e+00, 0.00000e+00, 0.00000e+00]])

In [12]:
svclassifier.n_support_

array([1, 2, 2, 4, 3, 2])

In [13]:
confusion_matrix(y_test, y_preds)

array([[23,  0,  0,  0,  0,  0],
       [ 0, 17,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  5,  0,  0],
       [ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0, 11]], dtype=int64)

In [14]:
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        17
           3       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         5
           6       1.00      1.00      1.00         4
           7       1.00      1.00      1.00        11

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [15]:
model1 = SVC(kernel = 'sigmoid')
model2 = SVC(kernel = 'poly')
model3 = SVC(kernel = 'rbf')

In [16]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

SVC()

In [17]:
ypred1 = model1.predict(X_test)
ypred2 = model2.predict(X_test)
ypred3 = model3.predict(X_test)

In [18]:
print(accuracy_score(y_test, ypred1))

0.5384615384615384


In [19]:
accuracy_score(y_test, ypred2)

0.9846153846153847

In [20]:
accuracy_score(y_test, ypred3)

0.7846153846153846

In [21]:
[{'kernel':['rbf'],'gamma':[1e-3,1e-4],
     'C':[1,10,100,1000]},
{'kernel':['linear'],'C':[1,10,100,1000]},
{'kernel':['poly'],'gamma':[1e-3,1e-4],'degree':[2,3,4]},
{'kernel':['sigmoid'],'C':[1,10,100,1000],'gamma':[1e-3,1e-4,1e-5]}]

[{'kernel': ['rbf'], 'gamma': [0.001, 0.0001], 'C': [1, 10, 100, 1000]},
 {'kernel': ['linear'], 'C': [1, 10, 100, 1000]},
 {'kernel': ['poly'], 'gamma': [0.001, 0.0001], 'degree': [2, 3, 4]},
 {'kernel': ['sigmoid'],
  'C': [1, 10, 100, 1000],
  'gamma': [0.001, 0.0001, 1e-05]}]

In [22]:
params_grid1=[{'kernel':['rbf']},
             {'kernel':['linear']},
             {'kernel':['poly']},
             {'kernel':['sigmoid']}]

In [23]:
from sklearn.model_selection import GridSearchCV
svm_model = GridSearchCV(SVC(), params_grid1, cv = 5)
svm_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'kernel': ['rbf']}, {'kernel': ['linear']},
                         {'kernel': ['poly']}, {'kernel': ['sigmoid']}])

In [24]:
print('Best score for training data:', svm_model.best_score_, "\n")

#View the best parameters for the model found using grid search
print('Best C:', svm_model.best_estimator_.C, "\n")
print('Best Kernel:', svm_model.best_estimator_.kernel, "\n")
print('Best Gamma:', svm_model.best_estimator_.gamma, "\n")

final_model = svm_model.best_estimator_
y_preds = final_model.predict(X_test)

Best score for training data: 0.9866666666666667 

Best C: 1.0 

Best Kernel: linear 

Best Gamma: scale 



In [25]:
accuracy_score(y_test, y_preds)

1.0